sudo: false
language: node_js
node_js:
  - stable
  - 4
install:
  - npm prune
  - npm update
after_success:
  - npm run coveralls
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: dominic@dbarnes.info
  api_key:
    secure: xmVWEt1aOi2kjPSpfyHQ9iUT6eRckLk4bGf3FggO3s2JwNKwQBcaoljY6UmpvF6TPEpf46onF8U8wFpWWPu9fKsCwM9WBhu+DjIOwaEDZs/7mEQwA67P560t2VPsh/3Kj/XylYtjuPc24XT3cvoT32pO8Ub8PyRXx0scAGbGCiKAIlNH2PO3fpqfs8QfAWxtugy+E/QEDGwAf16V5foVH2Q2ao8+XiWWDmeQqZNh9egU2pFUSNVqr9jf123Vrmay4c/qrnMaAafiUz7myMH5Neow2Dkw4dixkztjkZuENA4O1DJV8RgF3kfnWbDVGrOaK66sPcxRt2hUxEYgZFl4FcRQJTURWb5InRSeNO2OSwH7ZApfdsRe5X6VxFwqmZfxQDfZhXTGapmRJUbf5T+h1iF0m1xKalOPhff1a1tQc90nBhnaau285v0URiBr57q76ziQSVnvByoi9B85ROwkx3M8PvbIIcf9iiK+Snug0RLSCSFeZHErILAKRIIGUkGvn3we8v7MI2NZ+qzp+BtKFzG2dpYvCHUnqUODI2weeeeMR+hVcn0ppYi4YS6fNIYyqKSPSFURzm5ADB+zTwISfMt/l8TLCfJ2tFt/FwKkP9kH1yOOufEHJKu7W+BTovf1Cx5SCxF8o0vGgDcKajUThtxN37Xqag43jY0Li4PIQqY=
  on:
    tags: true
    repo: makojs/js
    node: stable
